name: integration-tests
run-name: python - Integration Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: docker-build
        run: docker buildx build -f docker/Dockerfile -t lsp-testing --load --cache-to=gha,cache --cache-from=gha .
      - name: docker-test
        run: docker run lsp-testing python -m pytest
